### ISSUE TITLE
一直报错啊

### ISSUE THREAD

**Issue by hogger0** [lltx/auth-server-demo#2]
![image](https://user-images.githubusercontent.com/6472032/130206097-af3de8f0-0b7a-430c-9711-aa32d59b0fef.png)
![image](https://user-images.githubusercontent.com/6472032/130206136-1fe8c87e-e60d-422d-96a5-4c651510ba26.png)

**Comment by dousp** [comment]
你看看你的授权码后面是不是多了个#号，https://pig4cloud.com/用着个重定向的地址会多加个#号，应该是前端定位用的吧。
你换成百度的就没有了
